version = 0.1
[default.deploy.parameters]
stack_name = "urlshortener"
resolve_s3 = true
s3_prefix = "urlshortener"
region = "eu-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
