AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener Serverless Application

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9

Resources:
  # Tabella DynamoDB per memorizzare le mappature degli URL
  UrlsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: url-shortener-urls
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: short_id
          AttributeType: S
      KeySchema:
        - AttributeName: short_id
          KeyType: HASH

  # Lambda per creare URL brevi
  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_short_url/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlsTable
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref UrlsTable
          # Rimosso il riferimento all'API Gateway qui, lo passeremo dopo il deploy
          API_ENDPOINT: "TEMPORANEO"

  # Lambda per reindirizzare all'URL originale
  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/redirect/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlsTable
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref UrlsTable

  # API Gateway con definizione OpenAPI
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: URLShortenerApi
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: URL Shortener API
        paths:
          /create:
            post:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateShortUrlFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
              responses: {}
          /{shortId}:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RedirectFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
              responses: {}
              parameters:
                - name: "shortId"
                  in: "path"
                  required: true
                  type: "string"
          /shorten:
            get:
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateShortUrlFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
              parameters:
                - name: "url"
                  in: "query"
                  required: true
                  type: "string"

  # Permission per Lambda CreateShortUrl
  CreateShortUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateShortUrlFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*"

  # Permission per Lambda Redirect
  RedirectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RedirectFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/GET/{shortId}"

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  CreateShortUrlFunction:
    Description: "Create Short URL Lambda Function ARN"
    Value: !GetAtt CreateShortUrlFunction.Arn
  RedirectFunction:
    Description: "Redirect Lambda Function ARN"
    Value: !GetAtt RedirectFunction.Arn